<?php include('src/commun/header.php'); ?>

<header class="header">

</header>

<section class="section section--left">
  <div class="information">
    <h1>Ludovic CHEVROULET</h1>
    Développeur junior
  </div>
  <div class="contact">
    <h2>Contactez moi</h2>
  </div>
</section>
<section class="section section--right">
  <div class="cv">
    <h2>Mon CV</h2>
  </div>
  <div class="project">
    <h2>Mes projets</h2>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum tempore quod facilis corrupti, voluptates aliquam adipisci enim repellat quia aliquid accusamus expedita accusantium modi cumque corporis voluptas perspiciatis voluptatibus quisquam.</div>
  </div>
</section>
<?php include('src/commun/footer.php'); ?>