-- MySQL Script generated by MySQL Workbench
-- Fri Feb 17 16:05:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portofolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portofolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portofolio` DEFAULT CHARACTER SET utf8 ;
USE `portofolio` ;

-- -----------------------------------------------------
-- Table `portofolio`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portofolio`.`tag` (
  `idtag` INT NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idtag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portofolio`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portofolio`.`type` (
  `idtype` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idtype`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portofolio`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portofolio`.`image` (
  `idimage` INT NOT NULL AUTO_INCREMENT,
  `name_img` VARCHAR(45) NULL,
  `alt_img` VARCHAR(45) NULL,
  PRIMARY KEY (`idimage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portofolio`.`row`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portofolio`.`row` (
  `idrow` INT NOT NULL AUTO_INCREMENT,
  `title_row` VARCHAR(45) NULL,
  `sub_title_row` VARCHAR(45) NULL,
  `desc_row` MEDIUMTEXT NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `type_idtype` INT NOT NULL,
  `image_idimage` INT NOT NULL,
  PRIMARY KEY (`idrow`),
  INDEX `fk_row_type1_idx` (`type_idtype` ASC) ,
  INDEX `fk_row_image1_idx` (`image_idimage` ASC) ,
  CONSTRAINT `fk_row_type1`
    FOREIGN KEY (`type_idtype`)
    REFERENCES `portofolio`.`type` (`idtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_row_image1`
    FOREIGN KEY (`image_idimage`)
    REFERENCES `portofolio`.`image` (`idimage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portofolio`.`tag_has_row`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portofolio`.`tag_has_row` (
  `tag_idtag` INT NOT NULL,
  `row_idrow` INT NOT NULL,
  PRIMARY KEY (`tag_idtag`, `row_idrow`),
  INDEX `fk_tag_has_row_row1_idx` (`row_idrow` ASC) ,
  INDEX `fk_tag_has_row_tag_idx` (`tag_idtag` ASC) ,
  CONSTRAINT `fk_tag_has_row_tag`
    FOREIGN KEY (`tag_idtag`)
    REFERENCES `portofolio`.`tag` (`idtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_has_row_row1`
    FOREIGN KEY (`row_idrow`)
    REFERENCES `portofolio`.`row` (`idrow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
